# Generated by Django 3.2.18 on 2023-02-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20230221_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_my_app_appuser_friends_+', to='my_app.AppUser'),
        ),
    ]
